spring.application.name=ACTIVITY-SERVICE
server.port=8082

# ===============================
# MongoDB local connection
# ===============================

spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=fitnessdb

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# ===============================
# Eureka
# ===============================
#Configuration is required to locate the Eureka server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}


# ===============================
# RabbitMQ (PRODUCER)
# ===============================

#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=admin
#spring.rabbitmq.password=admin123

spring.rabbitmq.addresses=${RABBITMQ_URL}

rabbitmq.exchange.name=fitness.exchange
rabbitmq.queue.name=activity.queue
rabbitmq.routing.key=activity.tracking

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=4

# ===============================
# Resilience4j Circuit Breaker
# ===============================

#If 3+ calls happen
#And 50% fail
#Circuit opens for 10 seconds

resilience4j.circuitbreaker.instances.userServiceCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.userServiceCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.userServiceCB.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.userServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userServiceCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.userServiceCB.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.userServiceCB.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.circuitbreaker.instances.userServiceCB.recordExceptions=\
org.springframework.web.reactive.function.client.WebClientResponseException,\
java.io.IOException

# ===============================
# Actuator
# ===============================

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#http://localhost:8082/actuator/circuitbreakers






