# Application name
#spring.application.name=api-gateway
spring.application.name=API-GATEWAY

# Server port
server.port=8080

# ==============================
# Front_End URL
# ==============================
frontend.url=${FRONTEND_URL}

# ==============================
# Spring Cloud Gateway Routes
# ==============================

# User Service
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# Activity Service
spring.cloud.gateway.routes[1].id=activity-service
spring.cloud.gateway.routes[1].uri=lb://ACTIVITY-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/activities/**

# AI Service
spring.cloud.gateway.routes[2].id=ai-service
spring.cloud.gateway.routes[2].uri=lb://AI-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/recommendations/**

# ==============================
# Eureka Client
# ==============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}

# OAuth2
#configuring oauth2 to talk to keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8181/realms/fitness-app/protocol/openid-connect/certs
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/fitness-oauth2


# Gateway Timeouts
spring.cloud.gateway.httpclient.connect-timeout=2000
spring.cloud.gateway.httpclient.response-timeout=5s


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.level.org.springframework.security=DEBUG

