#spring.application.name=user-service
spring.application.name=USER-SERVICE

#spring.datasource.url=jdbc:postgresql://localhost:5432/fitness-micro-user
#spring.datasource.username=postgres
#spring.datasource.password=SreeRama@005

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

#Configuration is required to locate the Eureka server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ===============================
# Actuator
# ===============================

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always




#http://localhost:8081/actuator/health
